# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6f47c806d015cb4ad9ac7c429258d6f6945e2a42b08ed195e1a1a91ae2fbb0b147b3bd6d68e7c012ffe3055780f8c0846bb2d11441cfedce68d2b06ade01cfa

test:
  secret_key_base: 411f0292c69d8561d3b0df58cb84e9280666d68d3dfcadb45c7ff73eaaa16b6407781317075430c2c1403543e5d1fa71bd0507fcc26093c0872729317ff0c71d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
